ignore:
  - "SwiftGenTemplates"
  - "URLShortenerTests"
  - "URLShortenerUITests"
  - "URLShortener/App/TestsSceneDelegate.swift"
  - "URLShortener/App/TestsAppDelegate.swift"
  - "URLShortener/App/main.swift"
  - "URLShortener/Resources"
